### ISSUE TITLE
isSorted is green for unsorted data

### ISSUE THREAD

**Issue by SKR301** [Akshayaap/algo-visualizer#4]
![image](https://user-images.githubusercontent.com/47807051/139559575-1ab54bfa-1fdf-4620-a652-3df9130046d0.png)

Happens after merging and then clicking "Generate New Array"

**Comment by Akshayaap** [comment]
Click on isSorted Button to check "UNDERLYING" Array is sorted or not.
it's the problem with UI itself, sometime UI is not correctly rendering original underlying array.

**Comment by SKR301** [comment]
Are you fixing it?

**Comment by Akshayaap** [comment]
Have to find better sleep () function equivalent.
